parameters:
    
   recherche: covoiturage.rechercheTrajet

services:
    covoiturage.rechercheTrajet:
        class: MyApp\CovoiturageBundle\Recherche\RechercheTrajet
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"

#    covoiturage.rechercheTrajetTest:
#        class: MyApp\CovoiturageBundle\Tests\Controller\TrajetControllerTest
#        arguments: 
#            recherche: "@covoiturage.rechercheTrajet"


    covoiturage.test:
         class: MyApp\CovoiturageBundle\Recherche\Test
         arguments: 
             entityManager: "@covoiturage.rechercheTrajet"