parameters:
#    my_app_covoiturage.example.class: MyApp\CovoiturageBundle\Example


#    my_app_covoiturage.example:
#        class: %my_app_covoiturage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    covoiturage.rechercheTrajet:
        class: MyApp\CovoiturageBundle\Recherche\RechercheTrajet
        arguments: [villeDepart, villeArrive, dateDepart]