parameters:
#    my_app_covoiturage.example.class: MyApp\CovoiturageBundle\Example

services:
#    my_app_covoiturage.example:
#        class: %my_app_covoiturage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
